nodeLinker: pnp
pnpMode: strict

packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.9.3
  "@parcel/types@*":
    dependencies:
      "@parcel/core": 2.9.3
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": 2.9.3