@startuml Point 'n Click

[Game content] --> [DSL System]
[DSL System] ..> JSON 
interface TranslationFile
component Theme

package "Game Engine" {
    TranslationFile ..> [ContentManager]
    JSON ..> [ContentManager]
    [StateManager] --> [ScriptRunner]
    [ContentManager] --> [ScriptRunner]

    [ScriptRunner] --> DisplayModel

    DisplayModel --> [ThemeSystem]
    [Theme] -> [ThemeSystem]
    [ThemeSystem] --> [InteractionHandler]
    [InteractionHandler] --> [ScriptRunner]
}

@enduml