@startuml Script Processing
actor GameScript order 1
queue Queue order 2
entity QueueuItemHandler as QH order 3 
control MessageBus as Bus order 4 
boundary MessageHandler as MH order 5 
database GameState order 1 

== Preparation ==

MH --> Bus: Add handler
note right: Message handlers are for displaying elements\non screen, playing sounds,\nwaiting for user interactions
QH --> Queue: Add handler
note right: QueItemHandlers process entire queue items, by chaining\nmulitple requests to the MessageBus, updating game state, etc.
Bus <-- Queue: Uses

== Execution ==

GameScript --> Queue: Add elements to queue

System --> GameState: Make snapshot\nof Game State

Queue --> Queue: Execute

loop Execute queue

    Queue --> QH: Process Item
    group one or more
        QH --> Queue: Request action/data
        Queue --> Queue: Log request
        Queue --> Bus: Request action/data
        Bus --> MH: Handle
        ...
        Queue <-- MH: Reply
        Queue --> Queue: Log reply
        Queue --> QH: Reply
    end
end

== Save State ==

System --> Queue: Get request/reply log
System --> System: Persist Log with snapshot\nof Game State

== Load State ==

System --> System: Load Log with snapshot\nof Game State
System --> GameState: Restore state
GameScript --> Queue: Add elements to queue
System --> Queue: Replay log



@enduml